sudo: false
language: java

dist: xenial

services:
  - mysql

jdk:
  - openjdk15
  - oraclejdk15

script:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - bash .travis-ci/database.sh
